englishonly: false

zeebe.client.cloud:
  clusterId: 3531791c-2bfe-4535-bff7-c711bbef2753
  clientId: J-.mL-~HqP~GTSJFh-Y1P1VYR20F6HDY
  clientSecret: fERyDt7L_7gSCq~DwX_Ee7fo7Q7ztGMMndKbKSGZugRsCLUl5Mj2rxHHZxeKx-3w

server:
  servlet:
    context-path: /camunda
