spring:
 datasource:
  url: 'jdbc:h2:file:~/testdb;DB_CLOSE_DELAY=-1;MVCC=TRUE'
  username: sa
  password: sa
 h2:
  console:
    enabled: true
    path: /h2-console
    settings:
        web-allow-others: true

englishonly: false

cawemo:
  enabled: 'false'
  url: '${CAWEMO_URL}'
  apiKey: '${CAWEMO_API_KEY}'
  orgId: '${CAWEMO_ORG_ID}'
  authMode: 'BASIC'
  projectName: 'Customer Onboarding'

server:
  servlet:
    context-path: /camunda
